package interfaces.editClass;

import objects.MyCourse;
import interfaces.MainFrame;
import interfaces.editClass.EditSelectedClass;

/**
 *
 * @author Lilong
 * @edited Justin
 */
public class AddNewStudent extends javax.swing.JPanel {

	private MainFrame parent;
	
    /**
     * Creates new form AddNewStudent
     */
	 public AddNewStudent(MainFrame mainFrame) {
	    	parent = mainFrame;
	        initComponents();
	 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	goBackButton = new javax.swing.JButton();
    	jScrollPane = new javax.swing.JScrollPane();
    	
    	goBackButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });
    	
    	
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
        		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goBackButton)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(goBackButton)
                    .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setAddNewStudentVisible(){
    	parent.setContentPane(this);
    	//addNewStudent.setVisible(true);
    	parent.simpleMode.setVisible(false);
    	parent.addNewClass.setVisible(false);
    	parent.currentCourseWindow.setVisible(false);    	
    	parent.pack();
    }
    
    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //this.setVisible(false);
    	parent.currentCourseWindow.setEditSelectedClassVisible();
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBackButton;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
