/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Container;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.JButton;

import objects.MyCourse;
import interfaces.MainFrame;
import interfaces.editClass.EditSelectedClass;
/**
 *
 * @author Lilong
 */
public class SimpleMode extends javax.swing.JPanel implements ActionListener {
	private MainFrame parent;
	private ArrayList<JButton> courseButtons = new ArrayList<JButton>();
    private javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    /**
     * Creates new form SimpleMode
     */
    public SimpleMode(MainFrame frame) {
    	parent = frame;
        initComponents();
        setup();
        getSimpleModeLayOut();
    }
    
    private void setup() {
    	for (int i = 0; i < parent.getCourses().size(); i++) {
    		JButton button = new JButton();
    		button.setFont(new java.awt.Font("Georgia", 0, 14));
    		button.setText(parent.getCourses().get(i).getName());
    		button.setVisible(true);
    		button.addActionListener(this);
    		courseButtons.add(button);
    	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Class", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     *those code are repeated from the above, Because we are not allowed to change the code above
     *therefore, I created my own layout here
     */
    public final void getSimpleModeLayOut() {
    	GroupLayout.ParallelGroup horizontal = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        GroupLayout.SequentialGroup vertical = layout.createSequentialGroup();
        
        vertical.addContainerGap();
        
    	for (int i = 0; i < courseButtons.size(); i++) {
    		horizontal.addComponent(courseButtons.get(i), javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE);
    		vertical.addComponent(courseButtons.get(i));
   			vertical.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
    	}
    	
    	vertical.addContainerGap(40, Short.MAX_VALUE);
    	
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(horizontal)
                .addContainerGap())
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vertical)
        );
    }
    
    public void actionPerformed(java.awt.event.ActionEvent evt) {
    	Object source = evt.getSource();
    	if (source instanceof JButton) {
    		int index = getButtonIndex((JButton)source);
    		//FIXME Should open EditSelectedClass and send parent.getCourses().get(index) as a constructor
    		EditSelectedClass currentCourse = new EditSelectedClass(parent);
    		parent.setEditSelectedClass(currentCourse);
    		parent.setContentPane(currentCourse);
    		parent.setEditSelectedClassVisible();
    		currentCourse.setPanelMenu();
    		//System.out.println(parent.getCourses().get(index).getName());
    	}
    }
    
    private int getButtonIndex(JButton button) {
        for (int i = 0; i < courseButtons.size(); i++) {
            if (button == courseButtons.get(i)) return i;
        }
        return -1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
