/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GhostGradeBook;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Lilong
 */
public class CurrentClass extends javax.swing.JPanel {
    public DefaultTableModel model;
    public ArrayList<String> courseData = new ArrayList<String>();
    /**
     * Creates new form CurrentClass
     */
    public CurrentClass() {
        initComponents();
        setup();
    }
    
    private void setup() {
        model = (DefaultTableModel) classTable.getModel();
        addClassButton.setActionCommand("createNewClass");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeClassButton = new javax.swing.JButton();
        addClassButton = new javax.swing.JButton();
        editClassButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        classTable = new javax.swing.JTable();

        removeClassButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        removeClassButton.setText("Remove Class");
        removeClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeClassButtonActionPerformed(evt);
            }
        });

        addClassButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        addClassButton.setText("Add new class");
        addClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassButtonActionPerformed(evt);
            }
        });

        editClassButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        editClassButton.setText("Edit/View Class");
        editClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClassButtonActionPerformed(evt);
            }
        });

        classTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Row", "Class Name", "Course Prefix", "Course Number", "Class Section", "Class Building", "Class Room Number", "Meeting Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(classTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void upDateWelcomeWindow() {
        model.addRow(new Object[]{null, null, null, null, null, null, null, null});
        for (int r = 0; r < classTable.getRowCount() - 1; r++) {
            if (classTable.getValueAt(r, 0) == null) {
                classTable.setValueAt(r, r, 0);
                for (int c = 0; c < classTable.getColumnCount() - 1; c++) {
                    classTable.setValueAt(courseData.get(c), r, c + 1);
                }
            }
        }
    }
    
    private void removeClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeClassButtonActionPerformed
        if (classTable.getSelectedRow() != -1) {
            if (classTable.getValueAt(classTable.getSelectedRow(), 0) != null) {
                int r = classTable.getSelectedRow();
                model.removeRow(classTable.getSelectedRow());
                while (classTable.getValueAt(r, 0) != null) {
                    classTable.setValueAt(r, r, 0);
                    r++;
                }
            }
        }
    }//GEN-LAST:event_removeClassButtonActionPerformed

    private void addClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_addClassButtonActionPerformed

    private void editClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClassButtonActionPerformed
        if (classTable.getSelectedRow() != -1) {
            if (classTable.getValueAt(classTable.getSelectedRow(), 0) != null) {
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_editClassButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addClassButton;
    public javax.swing.JTable classTable;
    private javax.swing.JButton editClassButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeClassButton;
    // End of variables declaration//GEN-END:variables
}
