/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GhostGradeBook;

//import GhostGradeBook.editClass.NewStudent;
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.*;
import javax.swing.table.DefaultTableModel;
 

/**
 *
 * @author Lilong
 */
public class WelcomeWindow extends javax.swing.JFrame {

    private JFileChooser fc;
    private AddNewClassWindow addNewClass;
    private GhostGradeBook.editClass.ClassRoom editCurrentClass;
    private DefaultTableModel model;
    private GhostGradeBook.editClass.NewStudent addStudent;
    

    /**
     * Creates new form WelcomeWindow
     */
    public WelcomeWindow() {
        initComponents();
        this.setLocation(400, 300);
        fc = new JFileChooser();
        addNewClass = new AddNewClassWindow(this, true);
        addNewClass.setLocation(500, 300);
        editCurrentClass = new GhostGradeBook.editClass.ClassRoom(this, true);
        editCurrentClass.setLocation(500, 300);
        model = (DefaultTableModel) classTable.getModel();
        addStudent = new GhostGradeBook.editClass.NewStudent(this, true);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ghostGradeBookLabel = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        currentClassesPanel = new javax.swing.JPanel();
        removeClassButton = new javax.swing.JButton();
        addClassButton = new javax.swing.JButton();
        editClassButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        classTable = new javax.swing.JTable();
        editClassPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        classRoomTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        addStudentButton = new javax.swing.JButton();
        removeStudentButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        classPropertiesButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        newAssignmentButton = new javax.swing.JButton();
        removeAssignmentButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        openFile = new javax.swing.JMenuItem();
        saveFile = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        cut = new javax.swing.JMenuItem();
        copy = new javax.swing.JMenuItem();
        paste = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ghostGradeBookLabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        ghostGradeBookLabel.setText("Ghost Grade Book");

        jSplitPane2.setDividerLocation(700);

        currentClassesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Classes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14), java.awt.Color.black)); // NOI18N
        currentClassesPanel.setPreferredSize(new java.awt.Dimension(555, 610));

        removeClassButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        removeClassButton.setText("Remove Class");
        removeClassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeClassButtonMouseClicked(evt);
            }
        });
        removeClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeClassButtonActionPerformed(evt);
            }
        });

        addClassButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        addClassButton.setText("Add new class");
        addClassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClassButtonMouseClicked(evt);
            }
        });
        addClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassButtonActionPerformed(evt);
            }
        });

        editClassButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        editClassButton.setText("Edit/View Class");
        editClassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editClassButtonMouseClicked(evt);
            }
        });
        editClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClassButtonActionPerformed(evt);
            }
        });

        classTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Row", "Class Name", "Course ID", "Course Number", "Class Section", "Class Building", "Class Room Number", "Meeting Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(classTable);
        classTable.getColumnModel().getColumn(0).setResizable(false);
        classTable.getColumnModel().getColumn(0).setPreferredWidth(11);

        javax.swing.GroupLayout currentClassesPanelLayout = new javax.swing.GroupLayout(currentClassesPanel);
        currentClassesPanel.setLayout(currentClassesPanelLayout);
        currentClassesPanelLayout.setHorizontalGroup(
            currentClassesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentClassesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editClassButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        currentClassesPanelLayout.setVerticalGroup(
            currentClassesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentClassesPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(currentClassesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClassButton)
                    .addComponent(removeClassButton)
                    .addComponent(editClassButton))
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(currentClassesPanel);

        editClassPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selected Class", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N

        classRoomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Studen Name", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(classRoomTable);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        addStudentButton.setText("Add_Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(addStudentButton);

        removeStudentButton.setText("Remove_Student");
        jToolBar1.add(removeStudentButton);
        jToolBar1.add(jSeparator2);

        classPropertiesButton.setText("Class_Properties");
        jToolBar1.add(classPropertiesButton);
        jToolBar1.add(jSeparator1);

        newAssignmentButton.setText("New_Assignment");
        newAssignmentButton.setFocusable(false);
        newAssignmentButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newAssignmentButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(newAssignmentButton);

        removeAssignmentButton.setText("Remove_Assignment");
        removeAssignmentButton.setFocusable(false);
        removeAssignmentButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeAssignmentButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(removeAssignmentButton);

        javax.swing.GroupLayout editClassPanelLayout = new javax.swing.GroupLayout(editClassPanel);
        editClassPanel.setLayout(editClassPanelLayout);
        editClassPanelLayout.setHorizontalGroup(
            editClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editClassPanelLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        editClassPanelLayout.setVerticalGroup(
            editClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editClassPanelLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane2.setRightComponent(editClassPanel);

        file.setText("File");

        openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openFile.setText("OpenFile");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        file.add(openFile);

        saveFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveFile.setText("SaveFile");
        saveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileActionPerformed(evt);
            }
        });
        file.add(saveFile);

        jMenuBar1.add(file);

        edit.setText("Edit");

        cut.setText("Cut");
        edit.add(cut);

        copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copy.setText("Copy");
        edit.add(copy);

        paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        paste.setText("Paste");
        edit.add(paste);

        jMenuBar1.add(edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ghostGradeBookLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ghostGradeBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        //lilong code:
        int returnVal = fc.showOpenDialog(WelcomeWindow.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            JOptionPane.showMessageDialog(null,
                    String.format("%100s", file.getName() + " is opened, but we will decide what file to be opened"));
            //lilong end 9/15
            //next task
        }
    }//GEN-LAST:event_openFileActionPerformed

    private void saveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileActionPerformed
        //lilong
        int returnVal = fc.showSaveDialog(WelcomeWindow.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            JOptionPane.showMessageDialog(null,
                    String.format("%100s", file.getName() + " is saved, but we will decide what type file to be saved"));
            //lilong end 9/15
            //next task
        }
    }//GEN-LAST:event_saveFileActionPerformed

    private void editClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClassButtonActionPerformed
        if (classTable.getSelectedRow() != -1) {
            if (classTable.getValueAt(classTable.getSelectedRow(), 0) != null) {
                //editCurrentClass.setVisible(true);
                //editClass.setVisible(true);
            }
        }
    }//GEN-LAST:event_editClassButtonActionPerformed

    private void editClassButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editClassButtonMouseClicked

    }//GEN-LAST:event_editClassButtonMouseClicked

    private void addClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassButtonActionPerformed
        addNewClass.pack();
        //intial the addNewClass windown
        addNewClass.actionStatus = "Waiting for new action";
        addNewClass.setVisible(true);
        if (addNewClass.actionStatus.equals("Add to table")) {
            model.addRow(new Object[]{null, null,null, null,null, null,null, null});
            for (int r = 0; r < classTable.getRowCount() - 1; r++) {
                if (classTable.getValueAt(r, 0) == null) {
                    classTable.setValueAt(r, r, 0);
                    for (int c = 0; c < classTable.getColumnCount() - 1; c++) {
                        classTable.setValueAt(addNewClass.dataFromNewClass[c], r, c + 1);
                    }
                }
            }
            addNewClass.repaint();
        }

        if (addNewClass.actionStatus.equals("Cancel")) {
            addNewClass.repaint();
        }
    }//GEN-LAST:event_addClassButtonActionPerformed

    private void addClassButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClassButtonMouseClicked

    }//GEN-LAST:event_addClassButtonMouseClicked

    private void removeClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeClassButtonActionPerformed
        if (classTable.getSelectedRow() != -1) {
            if (classTable.getValueAt(classTable.getSelectedRow(), 0) != null) {
                int r = classTable.getSelectedRow();
                model.removeRow(classTable.getSelectedRow());
                while (classTable.getValueAt(r, 0) != null) {
                    classTable.setValueAt(r, r, 0);
                    r++;
                }
            }
        }
    }//GEN-LAST:event_removeClassButtonActionPerformed

    private void removeClassButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeClassButtonMouseClicked

    }//GEN-LAST:event_removeClassButtonMouseClicked

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        addStudent.setVisible(true);
    }//GEN-LAST:event_addStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WelcomeWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton classPropertiesButton;
    private javax.swing.JTable classRoomTable;
    private javax.swing.JTable classTable;
    private javax.swing.JMenuItem copy;
    private javax.swing.JPanel currentClassesPanel;
    private javax.swing.JMenuItem cut;
    private javax.swing.JMenu edit;
    private javax.swing.JButton editClassButton;
    private javax.swing.JPanel editClassPanel;
    private javax.swing.JMenu file;
    private javax.swing.JLabel ghostGradeBookLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton newAssignmentButton;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JMenuItem paste;
    private javax.swing.JButton removeAssignmentButton;
    private javax.swing.JButton removeClassButton;
    private javax.swing.JButton removeStudentButton;
    private javax.swing.JMenuItem saveFile;
    // End of variables declaration//GEN-END:variables
}
